branches:
  only:
    - master
sudo: required
language: php
php:
  - '7.3'
  - '7.4'
  
env:
  - DB=mysql
 
before_script:
  - if [["DB"== "mysql"]];then mysql -e "create database IF NOT EXISTS d1965919;" -uroot; fi
  
script:
#  - phpunit --configuration phpunit.xml --testsuite PHPTests --coverage-text --coverage-clover=coverage.xml
   - phpunit Tests/secondTest.php --coverage-text --coverage-clover=coverage.xml 
after_success:
  - bash <(curl -s https://codecov.io/bash)
