# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.2.17
  # - 5.2
  # aliased to 5.3.29
  # - 5.3
  # aliased to a recent 5.4.x version
  # - 5.4
  # aliased to a recent 5.5.x version
  # - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  - hhvm
  
# Thing to install before the actual building process
install:
 - composer self-update # This should not be required, but it is always a good practice to update composer
 - composer install
 - composer require satooshi/php-coveralls:~1.0@stable # Require phpCoveralls

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 5.6
    - php: 7.0
    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS d1965919;" -uroot; fi
     - mkdir -p build/logs # Create a folder to store clover files

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: 
- phpunit --coverage-clover build/logs/clover.xml --test-suffix .php --colors --report-useless-tests Tests/testTest.php

# After success, run sh to bind coveralls
after_success:
- sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/coveralls -v; fi;'
