branches:
  only:
    - master
sudo: required
language: php
php:
  - '7.3'
  - '7.4'

services:
  - mysql
  
before_script:
  - mysql -e "create database IF NOT EXISTS d1965919;"
  - mysql -u root --password="" < Tests/travis.sql
  
script:
 - phpunit --configuration phpunit.xml --testsuite PHPTests --coverage-text --coverage-clover=coverage.xml
 #  - phpunit  --coverage-text --coverage-clover=coverage.xml ./Tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
