# Create Testuser
#CREATE USER 'dev'@'localhost' IDENTIFIED BY 'dev';
#GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP ON *.* TO 'dev'@'localhost';

# Create DB
CREATE DATABASE IF NOT EXISTS d1965919 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE d1965919;

# Create Table
CREATE TABLE IF NOT EXISTS STUDENT (
  STUDENT_NO varchar(20) NOT NULL,
  PASSWORD text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE STUDENT
  ADD PRIMARY KEY (STUDENT_NO);

# Add Data
INSERT INTO STUDENT(STUDENT_NO,PASSWORD) values('1234','123')
